// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnTkhRkBDZALGqwrVY0pmolUCesdIglwg',
    appId: '1:384364502874:web:4510bfcaa861e992be9d63',
    messagingSenderId: '384364502874',
    projectId: 'bites-466fc',
    authDomain: 'bites-466fc.firebaseapp.com',
    storageBucket: 'bites-466fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqNe7m_G47snt7Gi68_s8x5D1AVyz3gc',
    appId: '1:384364502874:android:c8b19e7f73861111be9d63',
    messagingSenderId: '384364502874',
    projectId: 'bites-466fc',
    storageBucket: 'bites-466fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4FLJXSxts2GLjoNDT9lCVVje0We8XYZk',
    appId: '1:384364502874:ios:28c24296bd4f338fbe9d63',
    messagingSenderId: '384364502874',
    projectId: 'bites-466fc',
    storageBucket: 'bites-466fc.appspot.com',
    iosBundleId: 'com.example.bites',
  );
}
